### ISSUE TITLE
dynamicopenvr incompatibility

### ISSUE THREAD

**Issue by fuyushi** [ToniMacaroni/Scribble#1]
as it says, using dynamicopenvr with customavatars makes it impossible to draw. I can open the menu and select stuff but actually drawing doesnt work with any button for me. Deleting all of dynamicopenvr and customavatars resolves the issue. 
Oculus cv1 on steamvr

**Comment by ToniMacaroni** [comment]
Scribble is incompatible with dynamicOpenVR.BeatSaber, since it overrides input handling.
You can still use CustomAvatars without dynamicOpenVR.BeatSaber (just make sure you have the base mod "DynamicOpenVR" installed).
